### ISSUE TITLE
Investigate the QC checks currently conducted by assessment groups

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-dev/TIC-TAQ#1]
Need to split this up a bit
- [x] #5 contact chairs of EGs, start with WGNSSK, to identify collaborators
- [ ] #6 Begin a list of QC checks conducted at WGNSSK
- [ ] #7 Collect the code used at WGNSSK and add to TIC-TAQ GitHub page

**Comment by odontaster** [comment]
Hey!, I just uploaded to the SharePoint a document where I resume the bullet points regarding QC I found in WGNSSK, HAWG and WGCSE. 
https://community.ices.dk/ExpertGroups/TIC-TAQ/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FExpertGroups%2FTIC-TAQ%2FShared%20Documents%2F04%2E%20Project%20work&FolderCTID=0x012000AA4E77F1EDD3334C81804999743E17AD&View=%7B6AAD84C3-2E54-4A16-9479-766136E781FE%7D
